# Generated by Django 4.2.7 on 2023-11-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img_peliculas')),
                ('pelicula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foro.pelicula')),
            ],
        ),
    ]
