# Generated by Django 4.2.7 on 2023-11-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_remove_pelicula_imagen_imagenpelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_peliculas'),
        ),
        migrations.DeleteModel(
            name='ImagenPelicula',
        ),
    ]
